routes.py
from flask import (
    session,
    redirect,
    url_for,
    render_template,
    request,
    Blueprint
)
from config import PUBLIC_ROOMS
import json
main = Blueprint('main', __name__)


@main.route('/')
def index():
    name = session.get('name', '')
    return render_template('index.html', public_rooms=PUBLIC_ROOMS, name=name)


@main.route('/enter', methods=['POST'])
def enter():
    """
    加入聊天室, 将 name 和 room 保存在 session 里
    """
    name = request.form.get('name', '').strip()
    if name != '':
        session['name'] = name
        # 自定义房间列表用 json 格式保存在 session 里
        rooms = json.loads(session.get('custom_rooms', '[]'))
        room = (request.form.get('customRoom') or request.form.get('selectRoom')).strip()
        session['room'] = room
        if room not in (rooms + PUBLIC_ROOMS):
            rooms.append(room)
            session['custom_rooms'] = json.dumps(rooms)
        return redirect(url_for('.chat'))
    else:
        return redirect(url_for('.index'))


@main.route('/chat')
def chat():
    name = session.get('name', '')
    if name == '':
        return redirect(url_for('.index'))
    else:
        r = session.get('room', PUBLIC_ROOMS[0])
        rs = json.loads(session.get('custom_rooms', '[]'))
        return render_template('chat.html', current_room=r, custom_rooms=rs, public_rooms=PUBLIC_ROOMS)

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>聊天室</title>
    <link href="https://cdn.bootcss.com/bootswatch/3.3.7/cosmo/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
    {% block head_static %}{% endblock %}
</head>
<body>
{% include 'base/navbar.html' %}
<div class="container" id="main">
    {% block main %}
    {% endblock %}
</div>

{% block body_static %}{% endblock %}
</body>
</html>

templates/base/navbar.html
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">WebSocket Chat</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">首页</a></li>
                <li><a href="https://github.com/enincc/chatroom">源码</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="http://www.enin.cc/">论坛</a></li>
                <li><a href="http://todo.enin.cc/">ToDo</a></li>
            </ul>
        </div>
    </div>
</nav>

templates/chat.html
{% extends 'base/base.html' %}
{% block head_static %}
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/socket.io/2.0.4/socket.io.slim.js"></script>
{% endblock %}
{% block main %}
    <div class="jumbotron">
        <input id="id-current-room" type="hidden" value="{{ current_room }}">
        <h2 id="id-rooms-title">聊天室</h2>
        <ul class="nav nav-tabs">
            {% for r in custom_rooms %}
                <li class="pull-right {% if r == current_room %}active{% endif %}">
                    <a class="chat-room" href="#id-tab-content" data-toggle="tab" aria-expanded="false">{{ r }}</a>
                </li>
            {% endfor %}
            {% for r in public_rooms %}
                <li class="{% if r == current_room %}active{% endif %}">
                    <a class="chat-room" href="#id-tab-content" data-toggle="tab" aria-expanded="false">{{ r }}</a>
                </li>
            {% endfor %}

        </ul>
        <div class="tab-content">
            <div id="id-chat-area" class="tab-pane fade active in well" id="id-tab-content">

{#                <textarea id="id-chat-area" cols="80" rows="16" disabled></textarea>#}

            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <input id="id-input-text" class="form-control" type="text" placeholder="输入聊天消息">
                <span class="input-group-btn">
                    <button id="id-button-send" class="btn btn-default" type="button">Button</button>
                </span>
            </div>
        </div>
    </div>

{% endblock %}

{% block body_static %}
    <script src='{{ url_for('static', filename='utils.js') }}'></script>
    <script src="{{ url_for('static', filename='chat.js') }}"></script>
{% endblock %}

templates/index.html
{% extends 'base/base.html' %}
{% block main %}
    <div class="well well-lg col-sm-4 col-sm-offset-4">
        <form class="form-horizontal" action="{{ url_for('main.enter') }}" method="POST">
            <fieldset>
                <legend>选择昵称和房间</legend>
                <div class="form-group">
                    <label for="id-username" class="col-xs-4 control-label">昵称</label>
                    <div class="col-xs-8">
                        <input class="form-control" id="id-username" type=text name="name" placeholder="Nickname" value="{{ name }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="id-selectRoom" class="col-xs-4 control-label">公共房间</label>
                    <div class="col-xs-8">
                        <select class="form-control" id="id-selectRoom" name="selectRoom">
                            {% for r in public_rooms %}
                                <option>{{ r }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id-customRoom" class="col-xs-4 control-label">自定义房间</label>
                    <div class="col-xs-8">
                        <input class="form-control" id="id-customRoom" type=text name="customRoom" placeholder="若房间不存在将自动创建">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-8 col-xs-offset-4">
                        <button type="submit" class="btn btn-primary btn-block">进入聊天室</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}